version: '3.8'
services:

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  transacoes:
    image: 'zupacademy/transacoes'
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      TRANSACTION_DELAY: 100000 # tempo em milisegunds

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  
  # propostas-mysql:
  #   image: mysql
  #   networks: 
  #     - production-networks
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 8785491
  #   ports: 
  #     - "3307:3306"

#   propostas-api:
#     build:
#       dockerfile: Dockerfile
#       context: .
#     restart: always
#     image: leonardocosta/propostaapi
#     container_name: propostaApi
#     environment:
#       DB_HOST: "jdbc:mysql://propostas-mysql:3306/proposta?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
#       DB_PASSWORD: 8785491  
#     ports:
#       - "8080:8080"
#     networks: 
#       - production-networks
#     depends_on: 
#       - "propostas-mysql"
# networks:
#   production-networks:
#     driver: bridge     
